name: CI

on:
  push:
    branches: [ main, feature/*, bugfix/* ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run Python script
        run: python src/main.py
      - name: Run JavaScript script
        run: node src/hello_world.js
